apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flow-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: ${DOCKER_IMAGE_REPO}/flow-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-host
              key: latest
        - name: DB_NAME
          value: "flow"
        - name: DB_USER
          value: "flow_user"
        - name: DB_PORT
          value: "5432"
        - name: DB_SSL
          value: "false"
        - name: PGSSLMODE
          value: "disable"
        - name: DB_POOL_MIN
          value: "2"
        - name: DB_POOL_MAX
          value: "10"
        - name: DB_POOL_IDLE_TIMEOUT
          value: "10000"
        - name: DB_POOL_CONNECTION_TIMEOUT
          value: "5000"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        - name: REDIS_HOST
          value: "10.128.0.3"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-project-id
              key: latest
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-private-key
              key: latest
        - name: FIREBASE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: firebase-client-email
              key: latest
        - name: AUTH_PROVIDER
          value: "firebase"
        - name: ALLOW_UNAUTHENTICATED
          value: "true"
        - name: VALID_API_KEYS
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: latest
        - name: CORS_ORIGIN
          valueFrom:
            secretKeyRef:
              name: cors-origin
              key: latest
        - name: LOG_LEVEL
          value: "info"
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-api-key
              key: latest
        - name: SMTP_FROM
          value: "noreply@flow.app"
        - name: FRONTEND_URL
          value: "https://flow.app"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
