version: '3.8'

services:
  flow-api:
    image: ${DOCKER_IMAGE:-us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/flow-registry/flow-api:latest}
    container_name: flow-api-local
    ports:
      - "4000:4000"
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s